// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const config = {
  schema: "prisma/schema.prisma",
  engine: "classic",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"] || "file:d:/zanjirenabodii/app/metro-line1-app/prisma/dev.db",
  },
} as unknown as Parameters<typeof defineConfig>[0];

export default defineConfig(config);
